// <auto-generated />
using System;
using EasyMoto.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyMoto.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EasyMoto.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf_cliente");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_cliente");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefone_cliente");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_cpf_cliente");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.ClienteLocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<Guid>("MotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("moto_id");

                    b.Property<string>("StatusLocacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Ativa")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_locacoes");

                    b.ToTable("locacoes", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nome_empresa");

                    b.HasKey("IdEmpresa")
                        .HasName("pk_empresas");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_cnpj");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Filial", b =>
                {
                    b.Property<int>("IdFilial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdFilial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFilial"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Cidade");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpresaId");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Endereco");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("Estado");

                    b.Property<string>("NomeFilial")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("NomeFilial");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("Pais");

                    b.HasKey("IdFilial")
                        .HasName("pk_filiais");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_filiais_empresa_id");

                    b.ToTable("filiais", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("Cpf");

                    b.Property<int>("FilialId")
                        .HasColumnType("integer")
                        .HasColumnName("FilialId");

                    b.Property<string>("NomeFuncionario")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("NomeFuncionario");

                    b.HasKey("Id")
                        .HasName("pk_funcionarios");

                    b.HasIndex("FilialId")
                        .HasDatabaseName("IX_funcionarios_FilialId");

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Localizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("StatusLoc")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status_loc");

                    b.Property<string>("ZonaVirtual")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("zona_virtual");

                    b.HasKey("Id")
                        .HasName("pk_localizacoes");

                    b.ToTable("localizacoes", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("integer")
                        .HasColumnName("AnoFabricacao");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Cor");

                    b.Property<int?>("LocacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("LocacaoId");

                    b.Property<int>("LocalizacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("LocalizacaoId");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("Marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("Placa");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("Status");

                    b.HasKey("Id")
                        .HasName("pk_motos");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("IX_motos_Placa");

                    b.ToTable("motos", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Operador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_operador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf_opr");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_opr");

                    b.Property<int>("FilialId")
                        .HasColumnType("integer")
                        .HasColumnName("filial_id");

                    b.Property<string>("NomeOperador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_opr");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("telefone_opr");

                    b.HasKey("Id")
                        .HasName("pk_operador");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_operador_cpf_opr");

                    b.HasIndex("FilialId")
                        .HasDatabaseName("ix_operador_filial_id");

                    b.ToTable("operador", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Patio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Andar")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Andar");

                    b.Property<int>("FilialId")
                        .HasColumnType("integer")
                        .HasColumnName("FilialId");

                    b.Property<string>("NomePatio")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("NomePatio");

                    b.Property<string>("TamanhoPatio")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("TamanhoPatio");

                    b.HasKey("Id")
                        .HasName("pk_patios");

                    b.HasIndex("FilialId")
                        .HasDatabaseName("IX_patios_FilialId");

                    b.ToTable("patios", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MotoId")
                        .HasColumnType("integer")
                        .HasColumnName("moto_id");

                    b.Property<string>("NumeroVaga")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_vaga");

                    b.Property<bool>("Ocupada")
                        .HasColumnType("boolean")
                        .HasColumnName("ocupada");

                    b.Property<int>("PatioId")
                        .HasColumnType("integer")
                        .HasColumnName("patio_id");

                    b.HasKey("Id")
                        .HasName("pk_vagas");

                    b.HasIndex("PatioId", "NumeroVaga")
                        .IsUnique()
                        .HasDatabaseName("ix_vagas_patio_id_numero_vaga");

                    b.ToTable("vagas", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.ClienteLocacao", b =>
                {
                    b.OwnsOne("EasyMoto.Domain.ValueObjects.Periodo", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("ClienteLocacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("Fim")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("fim");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("inicio");

                            b1.HasKey("ClienteLocacaoId");

                            b1.ToTable("locacoes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteLocacaoId")
                                .HasConstraintName("fk_locacoes_locacoes_id");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Filial", b =>
                {
                    b.HasOne("EasyMoto.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Filiais")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_filiais_empresas_empresa_id");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("EasyMoto.Domain.Entities.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_funcionarios_filiais_filial_id");

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Operador", b =>
                {
                    b.HasOne("EasyMoto.Domain.Entities.Filial", null)
                        .WithMany()
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operador_filiais_filial_id");
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Patio", b =>
                {
                    b.HasOne("EasyMoto.Domain.Entities.Filial", null)
                        .WithMany()
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patios_filiais_filial_id");
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Vaga", b =>
                {
                    b.HasOne("EasyMoto.Domain.Entities.Patio", null)
                        .WithMany("Vagas")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vagas_patios_patio_id");
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Filiais");
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Patio", b =>
                {
                    b.Navigation("Vagas");
                });
#pragma warning restore 612, 618
        }
    }
}
