// <auto-generated />
using System;
using EasyMoto.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EasyMoto.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250907075820_Sync_Model_20250907_0458")]
    partial class Sync_Model_20250907_0458
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyMoto.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLIENTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CPF_CLIENTE");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL_CLIENTE");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_CLIENTE");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TELEFONE_CLIENTE");

                    b.HasKey("IdCliente");

                    b.HasIndex("CpfCliente")
                        .IsUnique();

                    b.ToTable("CLIENTE", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Locacao", b =>
                {
                    b.Property<int>("IdLocacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOCACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocacao"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLIENTE_ID");

                    b.Property<string>("StatusLocacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS_LOCACAO");

                    b.HasKey("IdLocacao");

                    b.ToTable("LOCACAO", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Moto", b =>
                {
                    b.Property<int>("IdMoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MOTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMoto"));

                    b.Property<int>("Ano")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANO");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PLACA");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("IdMoto");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("MOTO", (string)null);
                });

            modelBuilder.Entity("EasyMoto.Domain.Entities.Locacao", b =>
                {
                    b.OwnsOne("EasyMoto.Domain.ValueObjects.Periodo", "Periodo", b1 =>
                        {
                            b1.Property<int>("LocacaoIdLocacao")
                                .HasColumnType("NUMBER(10)");

                            b1.Property<DateTime>("Fim")
                                .HasColumnType("TIMESTAMP(7)")
                                .HasColumnName("DATA_FIM");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("TIMESTAMP(7)")
                                .HasColumnName("DATA_INICIO");

                            b1.HasKey("LocacaoIdLocacao");

                            b1.ToTable("LOCACAO");

                            b1.WithOwner()
                                .HasForeignKey("LocacaoIdLocacao");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
